version: "3.4"

services:
  client:
    image: ${GITHUB_USERNAME-rep}/atir-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 3001
      BACKEND_URL: http://206.189.109.20:9090/
    ports:
      - "8080:3001"
    volumes:
      - "/etc/hosts:/etc/hosts"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
